"""add published_to_staging column to assignments

Revision ID: 171e5e2dcb4d
Revises: 4642a1c5014d
Create Date: 2024-07-26 17:23:43.470565+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171e5e2dcb4d'
down_revision = '4642a1c5014d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('published_to_staging', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'published_to_staging')
    # ### end Alembic commands ###
