"""Change User role_id foreign key to a role_name foriegn key

Revision ID: 27622169eb7d
Revises: 6d647b5d5baa
Create Date: 2023-08-24 15:54:08.386098+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27622169eb7d'
down_revision = '6d647b5d5baa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('role_name', sa.Text(), nullable=False))
    op.drop_constraint('user_account_role_id_fkey', 'user_account', type_='foreignkey')
    op.create_foreign_key(None, 'user_account', 'user_role', ['role_name'], ['name'])
    op.drop_column('user_account', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.create_foreign_key('user_account_role_id_fkey', 'user_account', 'user_role', ['role_id'], ['id'])
    op.drop_column('user_account', 'role_name')
    # ### end Alembic commands ###
