"""Add join_date and exit_date to student model.

Revision ID: 38c44ed382f8
Revises: dbbc2a5f3ddf
Create Date: 2023-08-01 00:34:52.369070+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c44ed382f8'
down_revision = 'dbbc2a5f3ddf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('join_date', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('student', sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'exit_date')
    op.drop_column('student', 'join_date')
    # ### end Alembic commands ###
