"""Add staging repo url to course

Revision ID: 4642a1c5014d
Revises: 395f7e014eef
Create Date: 2024-07-25 21:13:41.660503+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4642a1c5014d'
down_revision = '395f7e014eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('staging_remote_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'staging_remote_url')
    # ### end Alembic commands ###
