"""Add student fork_remote_url field to track the remote of student forks

Revision ID: 675a2d5b61b4
Revises: 4e5e958c939f
Create Date: 2024-03-27 22:14:10.186010+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675a2d5b61b4'
down_revision = '4e5e958c939f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assignment', ['name'])
    op.add_column('student', sa.Column('fork_remote_url', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'fork_remote_url')
    op.drop_constraint(None, 'assignment', type_='unique')
    # ### end Alembic commands ###
