"""Make course start/end dates nullable

Revision ID: 696b0e252f90
Revises: ce961975d125
Create Date: 2024-06-03 18:19:23.078111+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '696b0e252f90'
down_revision = 'ce961975d125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('course', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'user_onyen_pid', ['onyen'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_onyen_pid', type_='unique')
    op.alter_column('course', 'end_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('course', 'start_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
