"""Change user role permission association table to use role name/permission name instead of ids for better clarity

Revision ID: 6d647b5d5baa
Revises: 47a490565a48
Create Date: 2023-08-23 19:26:49.539465+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d647b5d5baa'
down_revision = '47a490565a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role_permission', sa.Column('role_name', sa.Text(), nullable=True))
    op.add_column('user_role_permission', sa.Column('permission_name', sa.Text(), nullable=True))
    op.drop_constraint('user_role_permission_role_id_permission_id_key', 'user_role_permission', type_='unique')
    op.create_unique_constraint(None, 'user_role_permission', ['role_name', 'permission_name'])
    op.drop_constraint('user_role_permission_role_id_fkey', 'user_role_permission', type_='foreignkey')
    op.drop_constraint('user_role_permission_permission_id_fkey', 'user_role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'user_role_permission', 'user_role', ['role_name'], ['name'])
    op.create_foreign_key(None, 'user_role_permission', 'user_permission', ['permission_name'], ['name'])
    op.drop_column('user_role_permission', 'permission_id')
    op.drop_column('user_role_permission', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role_permission', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_role_permission', sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_role_permission', type_='foreignkey')
    op.drop_constraint(None, 'user_role_permission', type_='foreignkey')
    op.create_foreign_key('user_role_permission_permission_id_fkey', 'user_role_permission', 'user_permission', ['permission_id'], ['id'])
    op.create_foreign_key('user_role_permission_role_id_fkey', 'user_role_permission', 'user_role', ['role_id'], ['id'])
    op.drop_constraint(None, 'user_role_permission', type_='unique')
    op.create_unique_constraint('user_role_permission_role_id_permission_id_key', 'user_role_permission', ['role_id', 'permission_id'])
    op.drop_column('user_role_permission', 'permission_name')
    op.drop_column('user_role_permission', 'role_name')
    # ### end Alembic commands ###
