"""Update User table to have name and not first/last name

Revision ID: 7aa83f25debb
Revises: 8b4370f13b44
Create Date: 2024-05-17 14:25:38.958698+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa83f25debb'
down_revision = '8b4370f13b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('name', sa.Text(), nullable=False))
    op.alter_column('user_account', 'role',
               existing_type=sa.TEXT(),
               type_=app.core.role_permissions.UserRoleType(length=64),
               existing_nullable=False)
    op.drop_column('user_account', 'first_name')
    op.drop_column('user_account', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_account', sa.Column('first_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('user_account', 'role',
               existing_type=app.core.role_permissions.UserRoleType(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('user_account', 'name')
    # ### end Alembic commands ###
