"""Add published column to assignments table

Revision ID: 81b093623398
Revises: 395f7e014eef
Create Date: 2024-08-07 18:51:59.822706+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b093623398'
down_revision = '395f7e014eef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('is_published', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'is_published')
    # ### end Alembic commands ###
