"""Add base_extra_time column to student table

Revision ID: 8dd5af23b1f2
Revises: 977467e168ed
Create Date: 2023-07-31 22:44:22.984138+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd5af23b1f2'
down_revision = '977467e168ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('base_extra_time', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'base_extra_time')
    # ### end Alembic commands ###
