"""Move user password into separate user_auth table and rename to autogen_password_hash

Revision ID: 9567f2421e2f
Revises: 00231e6c6d18
Create Date: 2023-09-11 20:53:56.893997+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9567f2421e2f'
down_revision = '00231e6c6d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auto_password_auth',
    sa.Column('onyen', sa.String(), nullable=False),
    sa.Column('autogen_password_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['onyen'], ['user_account.onyen'], ),
    sa.PrimaryKeyConstraint('onyen')
    )
    op.drop_column('user_account', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('password', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_table('user_auto_password_auth')
    # ### end Alembic commands ###
