"""Add user roles/permissions

Revision ID: 97ed132b2f70
Revises: 0babbb4e741d
Create Date: 2023-08-11 21:11:30.944209+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ed132b2f70'
down_revision = '0babbb4e741d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_permission_id'), 'user_permission', ['id'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_table('user_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['user_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_user_role_permission_id'), 'user_role_permission', ['id'], unique=False)
    op.alter_column('student', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('user_account', sa.Column('role_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_id', table_name='user_account')
    op.drop_index('ix_user_onyen', table_name='user_account')
    op.create_index(op.f('ix_user_account_id'), 'user_account', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_onyen'), 'user_account', ['onyen'], unique=True)
    op.create_foreign_key('user_account_role_id_fkey', 'user_account', 'user_role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_account_role_id_fkey', 'user_account', type_='foreignkey')
    op.drop_index(op.f('ix_user_account_onyen'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_id'), table_name='user_account')
    op.create_index('ix_user_onyen', 'user_account', ['onyen'], unique=False)
    op.create_index('ix_user_id', 'user_account', ['id'], unique=False)
    op.drop_column('user_account', 'role_id')
    op.alter_column('student', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('student_id_seq'::regclass)"),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_role_permission_id'), table_name='user_role_permission')
    op.drop_table('user_role_permission')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_permission_id'), table_name='user_permission')
    op.drop_table('user_permission')
    # ### end Alembic commands ###
