"""Add max attempts field to assignment

Revision ID: a3908608c275
Revises: ce961975d125
Create Date: 2024-07-17 17:54:23.824562+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3908608c275'
down_revision = 'ce961975d125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('max_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'max_attempts')
    # ### end Alembic commands ###
