"""add manual grading field

Revision ID: bdf5e21a88df
Revises: 81b093623398
Create Date: 2024-08-26 17:50:41.774644+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf5e21a88df'
down_revision = '81b093623398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('manual_grading', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'manual_grading')
    # ### end Alembic commands ###
