"""PID-Onyen mapping table

Revision ID: ce961975d125
Revises: fa4753e5cede
Create Date: 2024-05-29 18:18:29.252894+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce961975d125'
down_revision = 'fa4753e5cede'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onyen_pid',
    sa.Column('onyen', sa.String(), nullable=False),
    sa.Column('pid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['onyen'], ['user_account.onyen'], ),
    sa.PrimaryKeyConstraint('onyen'),
    sa.UniqueConstraint('onyen'),
    sa.UniqueConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_onyen_pid')
    # ### end Alembic commands ###
