"""Canvas changes

Revision ID: fa4753e5cede
Revises: 7aa83f25debb
Create Date: 2024-05-29 18:16:32.918669+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4753e5cede'
down_revision = '7aa83f25debb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assignment', ['name'])
    op.add_column('course', sa.Column('start_at', sa.DateTime(), nullable=False))
    op.add_column('course', sa.Column('end_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'end_at')
    op.drop_column('course', 'start_at')
    op.drop_constraint(None, 'assignment', type_='unique')
    # ### end Alembic commands ###
